### PR TITLE
ENH `MuReNNDirect.to_conv1d()`

### PR DESCRIPTION
**Pull request by xir4n**
What's Changed:  

1. Added a new feature `to_conv1d` as described in #45.
2. MuReNNDirect now supports a variable number of Conv1d filters per scale. To specify the number of filters for each scale, use a list ~~or dictionary~~ instead of an integer.
3. The `Conv1d` kernel sizes in `MuReNNDirect` are no longer equal to the `T`; they are now equal to `T * Q[j]` where `Q[j]` is the number of filters per octave at octave `j`.
4. Added `J_phi` to specify the number of levels of downsampling in `MuReNNDirect`.
5. The output tensor shape of `MuReNNDirect` has been changed from a 5-dimensional tensor with shape `(B, C, Q, J, T)` to a 4-dimensional tensor with shape `(B, C, sum(Q_j * j), T//2**J_phi)`. This is a breaking change.

### CODE REVIEW

**Comment by lostanlen** [comment]
Another breaking change is that `MuReNNDirect` now uses `alternate_gh=False`. @xir4n says it's better-conditioned in terms of frame bounds, particularly when the input length is not a power of two.

**Review by lostanlen — APPROVED** [review]
👏🏻 👏🏻 👏🏻 👏🏻 👏🏻

**Comment by xir4n** [comment]
remove properties, conflict revolved

**Review by lostanlen — APPROVED** [review]
Excellent work.

This will require detailed release notes !

**Pull request merged**
